kind: pipeline
name: default

steps:
- name: build  
  image: plugins/docker
  settings:
    repo: ilshidur/nicolas-coutin.fr
    tags: latest
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
- name: deploy  
  image: appleboy/drone-ssh
  host: ${HOST}
  port: 22
  secrets:
    - username: [ssh_username]
    - password: [ssh_password]
  environment:
    TRAEFIK_NETWORK:
      from_secret: TRAEFIK_NETWORK
    RECAPTCHA_KEY:
      from_secret: RECAPTCHA_KEY
    RECAPTCHA_SECRET:
      from_secret: RECAPTCHA_SECRET
    MAILGUN_API_KEY:
      from_secret: MAILGUN_API_KEY
    MAILGUN_DOMAIN:
      from_secret: MAILGUN_DOMAIN
    MY_EMAIL:
      from_secret: MY_EMAIL
  script:
    - export DOMAIN=nicolas-coutin.fr
    - export TRAEFIK_NETWORK=$TRAEFIK_NETWORK
    - export RECAPTCHA_KEY=$RECAPTCHA_KEY
    - export RECAPTCHA_SECRET=$RECAPTCHA_SECRET
    - export MAILGUN_API_KEY=$MAILGUN_API_KEY
    - export MAILGUN_DOMAIN=$MAILGUN_DOMAIN
    - export MY_EMAIL=$MY_EMAIL
    - cd ~/projects/nicolas-coutin.fr
    - docker-compose pull
    - docker-compose up --build -d
