kind: pipeline
name: default

steps:
- name: docker  
  image: plugins/docker
  settings:
    repo: ilshidur/nicolas-coutin.fr
    tags: latest
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
- name: ssh  
  image: appleboy/drone-ssh
  host: evoli.nicolas-coutin.fr
  port: 22
  secrets: [ ssh_username, ssh_password ]
  envs: [ TRAEFIK_NETWORK, RECAPTCHA_KEY, RECAPTCHA_SECRET, MAILGUN_API_KEY, MAILGUN_DOMAIN, MY_EMAIL ]
  script:
    - export DOMAIN=nicolas-coutin.fr
    - export TRAEFIK_NETWORK=$TRAEFIK_NETWORK
    - export RECAPTCHA_KEY=$RECAPTCHA_KEY
    - export RECAPTCHA_SECRET=$RECAPTCHA_SECRET
    - export MAILGUN_API_KEY=$MAILGUN_API_KEY
    - export MAILGUN_DOMAIN=$MAILGUN_DOMAIN
    - export MY_EMAIL=$MY_EMAIL
    - cd ~/projects/nicolas-coutin.fr
    - docker-compose pull
    - docker-compose up --build -d
