version: '3'

services:
  nicolas-coutin-fr:
    image: ilshidur/nicolas-coutin.fr
    container_name: nicolas-coutin-fr
    restart: always
    networks:
      - proxy
    environment:
      - DOMAIN
      - RECAPTCHA_KEY
      - RECAPTCHA_SECRET
      - MAILGUN_API_KEY
      - MAILGUN_DOMAIN
      - MY_EMAIL
    labels:
      - traefik.enable=true
      - traefik.backend=nicolas-coutin-fr
      - traefik.frontend.rule=Host:${DOMAIN},www.${DOMAIN}
      - traefik.frontend.redirect.regex=^https?://www.${DOMAIN}/(.*)
      - traefik.frontend.redirect.replacement=https://${DOMAIN}/$${1}
      - traefik.docker.network=${TRAEFIK_NETWORK}
      - traefik.port=3000

networks:
  proxy:
    external:
      name: ${TRAEFIK_NETWORK}
