version: '3.7'

services:

  nicolas-coutin-com:
    build:
      context: .
    container_name: nicolas-coutin-com
    restart: always
    networks:
      - proxy
    env_file: .env
    labels:
      - traefik.enable=true
      - traefik.backend=nicolas-coutin-com
      - traefik.frontend.rule=Host:${DOMAIN},www.${DOMAIN}
      - traefik.frontend.redirect.regex=^https?://www.${DOMAIN}/(.*)
      - traefik.frontend.redirect.replacement=https://${DOMAIN}/$${1}
      - traefik.docker.network=${TRAEFIK_NETWORK}
      - traefik.port=3000

networks:
  proxy:
    external:
      name: ${TRAEFIK_NETWORK}
