version: '3'

services:
  nicolas-coutin-com:
    image: ilshidur/nicolas-coutin.com
    container_name: nicolas-coutin-com
    restart: always
    networks:
      - proxy
    environment:
      - DOMAIN
      - RECAPTCHA_KEY
      - RECAPTCHA_SECRET
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - MY_EMAIL
    labels:
      - traefik.enable=true
      - traefik.backend=nicolas-coutin-com
      - traefik.frontend.rule=Host:${DOMAIN},www.${DOMAIN}
      - traefik.frontend.redirect.regex=^https?://www.${DOMAIN}/(.*)
      - traefik.frontend.redirect.replacement=https://${DOMAIN}/$${1}
      - traefik.docker.network=${TRAEFIK_NETWORK}
      - traefik.port=3000

networks:
  proxy:
    external:
      name: ${TRAEFIK_NETWORK}
