name: Deployment

on:
  push:
    branches:
    - master

jobs:
  deploy:
    name: Build + Push ilshidur/nicolas-coutin.com/nicolas-coutin-com image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Log into Docker registry
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login -u Ilshidur --password-stdin docker.pkg.github.com
    - name: Build docker.pkg.github.com/ilshidur/nicolas-coutin.com/nicolas-coutin-com image
      run: docker build -t docker.pkg.github.com/ilshidur/nicolas-coutin.com/nicolas-coutin-com .
    - name: Push docker.pkg.github.com/ilshidur/nicolas-coutin.com/nicolas-coutin-com image
      run: docker push docker.pkg.github.com/ilshidur/nicolas-coutin.com/nicolas-coutin-com
    - name: Discord notif. error
      if: failure()
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      uses: Ilshidur/action-discord@master
      with:
        args: 'Error deploying : https://nicolas-coutin.com. For more informations, see https://github.com/Ilshidur/nicolas-coutin.com/actions.'
